### ISSUE TITLE
A library to simplify iOS animations in Swift.

### ISSUE THREAD

**Issue by RobertZh** [Tim9Liu9/TimLiu-iOS#96]
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

**Comment by mrhyh** [comment]
已经添加

**Comment by beyondverage0908** [comment]
😯




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            Swiftly Hot (Hot Avg)
                            
                            
                                
                                    邮箱：beyondaverage0908@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年04月28日 13:26，与狼共舞 写道： 已经添加

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tim9Liu9/TimLiu-iOS","title":"Tim9Liu9/TimLiu-iOS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Tim9Liu9/TimLiu-iOS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrhyh in #96: 已经添加"}],"action":{"name":"View Issue","url":"https://github.com/Tim9Liu9/TimLiu-iOS/issues/96#issuecomment-385141871"}}}
